import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LogoutButton from "./components/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-blue-900 w-[100%] flex px-4 py-2 font-[`Inter`] text-white font-bold mb-5 justify-between"><div className="flex ">
          <Link className="pr-2 border-r" href={"/"}>Home</Link>
          <Link className="pl-2" href={"/addJob"}>+Add job</Link>
          </div>
          <LogoutButton/>
        </nav>
        
        
        
        {children}</body>
    </html>
  );
}
